In [ ]:
import numpy as np

matrix_original = np.array([[1, 1, 0, 0, 0], [1, 1, 0, 0, 0], 
                   [0, 0, 1, 1, 1], [0, 0, 1, 1, 1], [0, 0, 1, 1, 1]])

print(np.round(np.linalg.eigvals(matrix_original), 3))

[ 2.  0. -0.  3. -0.]


In [11]:
matrix_compact = 0.5 * np.eye(2)
J = np.zeros((5, 2))
J[:2,0] = 1
J[2:,1] = 1

print(np.round(np.linalg.eigvals(J@matrix_compact@J.T), 3))
print(np.round(np.linalg.eigvals(matrix_compact), 3))

[ 1.   0.  -0.   1.5 -0. ]
[0.5 0.5]


In [7]:
print(np.round(np.linalg.eigvals(0.5 * np.eye(4)), 3))

[0.5 0.5 0.5 0.5]


In [13]:
mx = 1.99 * np.ones((3, 3))

mx[0,0] = 2
mx[1,1] = 2
mx[2,2] = 2

print(np.round(np.linalg.eigvals(mx), 3))


[0.01 5.98 0.01]
